### ISSUE TITLE
trezorctl: receiving error "Failed to enumerate WebUsbTransport"

### ISSUE THREAD

**Issue by lihaibh** [trezor/trezor-firmware#1860]
When i try to run any command of `trezorctl` i receive the following error:
```
Failed to enumerate WebUsbTransport. USBErrorOther: LIBUSB_ERROR_OTHER [-99]
```
this is too generic error and i dont know how to fix that.
The `trezorctl` cli worked for me before nothing changed.
It shows this error whether or not i plug in a trezor device.

tried also this command: `trezorctl usb-reset`
and received this error:
```
Traceback (most recent call last):
  File "/root/crypto/bin/trezorctl", line 8, in <module>
    sys.exit(cli())
  File "/root/crypto/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/root/crypto/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/root/crypto/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/crypto/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/crypto/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/root/crypto/lib/python3.9/site-packages/trezorlib/cli/trezorctl.py", line 291, in usb_reset
    WebUsbTransport.enumerate(usb_reset=True)
  File "/root/crypto/lib/python3.9/site-packages/trezorlib/transport/webusb.py", line 115, in enumerate
    cls.context.open()
  File "/root/crypto/lib/python3.9/site-packages/usb1/__init__.py", line 2139, in open
    mayRaiseUSBError(libusb1.libusb_init(byref(self.__context_p)))
  File "/root/crypto/lib/python3.9/site-packages/usb1/__init__.py", line 127, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/root/crypto/lib/python3.9/site-packages/usb1/__init__.py", line 119, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorOther: LIBUSB_ERROR_OTHER [-99]
```

`trezorctl` does works with trezor bridge though, it tries first to connect using the webusb that gives this error: `Failed to enumerate WebUsbTransport. USBErrorOther: LIBUSB_ERROR_OTHER [-99]` and than use the bridge that works.
Maybe i need to update drivers using zadig-2.6 but i dont know what i need to configure there.

Environment details:
OS: Windows 10 Pro
trezorctl version: 0.12.4
python version: 3.9.6
execution environment: ZSH through WSL terminal

**Comment by matejcik** [comment]
Could be a permissions problem too. Try running the console as admin and see if it helps.

If bridge works, you can instruct trezorctl to communicate through bridge, by running `trezorctl -p bridge` before the command you want
