### ISSUE TITLE
sh build-docker.sh doesn't build.

### ISSUE THREAD

**Issue by steffi1** [trezor/trezor-firmware#2012]
**Describe the bug**
build-docker.sh errors when executed.

**Firmware version and revision**
https://github.com/trezor/trezor-core.git

**Desktop/smartphone setup (please complete the following information):**
 macOS Monterey

sh build-docker.sh
.....
tools/binctl build/bootloader/bootloader.bin -s 1:2 `tools/keyctl sign bootloader build/bootloader/bootloader.bin 4141414141414141414141414141414141414141414141414141414141414141 4242424242424242424242424242424242424242424242424242424242424242`
Traceback (most recent call last):
  File "tools/keyctl", line 63, in <module>
    cli()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "tools/keyctl", line 58, in sign
    cosi.verify(sig, digest, global_pk)
TypeError: verify() missing 2 required positional arguments: 'keys' and 'mask'
Traceback (most recent call last):
  File "tools/binctl", line 359, in <module>
    main()
  File "tools/binctl", line 349, in main
    signature = binascii.unhexlify(sys.argv[4])
IndexError: list index out of range
scons: *** [build/bootloader/bootloader.bin] Error 1
Makefile:113: recipe for target 'build_bootloader' failed
make: *** [build_bootloader] Error 2

**Comment by prusnak** [comment]
please don't use trezor-core repo but use this repo instead: https://github.com/trezor/trezor-firmware
