### ISSUE TITLE
Python-Trezor error with prev_txes

### ISSUE THREAD

**Issue by d1vo1t** [trezor/trezor-firmware#308]
I followed the test cases and constructed this code as I am trying to execute this legacy transaction using python-trezor having trouble with the below error ! 

```
from trezorlib import btc, messages as proto
from trezorlib.tools import H_, CallException, btc_hash, parse_path
from trezorlib import device
from trezorlib.debuglink import TrezorClientDebugLink
from trezorlib.transport import enumerate_devices, get_transport
from trezorlib.client import get_default_client
import requests
import json

from trezorlib import coins
from trezorlib.tx_api import json_to_tx

inp1 = proto.TxInputType(
    address_n=parse_path("44'/1'/0'/0/0"),
    amount=4521464,
    prev_hash=bytes.fromhex("INPUT_TX_ID"),
    prev_index=0,
    script_type= proto.InputScriptType.SPENDADDRESS,
)

out1 = proto.TxOutputType(
    address="OUT1",
    amount=1000000,
    script_type=proto.OutputScriptType.PAYTOADDRESS,
)

out2 = proto.TxOutputType(
    address="OUT2",
    amount=4521464 - 1000000 - 20000,
    script_type=proto.OutputScriptType.PAYTOADDRESS,
)


rsz = requests.get(url='https://test-insight.bitpay.com/api/tx/INPUT_TX_ID')
coin_data = coins.by_name["Testnet"]
TXAPI = json_to_tx(coin_data, rsz.json())


client = get_default_client()
_, serialized_tx = btc.sign_tx(
    client, "Testnet", [inp1], [out1, out2], prev_txes = TXAPI
)
print(serialized_tx.hex())
```
ERROR
```
Traceback (most recent call last):
  File "tx.py", line 43, in <module>
    client, "Testnet", [inp1], [out1, out2], prev_txes = TXAPI
  File "/vxx/txbt/env/lib/python3.6/site-packages/trezorlib/tools.py", line 233, in wrapped_f
    return f(client, *args, **kwargs)
  File "/vxx/txbt/env/lib/python3.6/site-packages/trezorlib/btc.py", line 108, in sign_tx
    raise ValueError("Could not retrieve prev_tx") from e
ValueError: Could not retrieve prev_tx

```

**Comment by matejcik** [comment]
`prev_txes` must be a dictionary of tx hashes
so instead of your `TXAPI` line, use something like:
```
prev_txes = { bytes.fromhex("INPUT_TX_ID"): coin_data }
btc.sign_tx(..., prev_txes=prev_txes)
```
