### ISSUE TITLE
Race condition when signing NEM transactions on emulator with DebugLink

### ISSUE THREAD

**Issue by mlejva** [trezor/trezor-firmware#67]
I managed to reproduce this race condition approximately 6 times out of total 10 runs.

I'm using [connect](https://github.com/trezor/connect/tree/tests/connect) together with an emulator. The emulator is [loaded](https://github.com/trezor/connect/blob/tests/connect/src/__tests__/init_device.py) with DebugLink. 
Transport is [started](https://github.com/trezor/connect/blob/tests/connect/src/__tests__/run.sh#L150-L164) with both the emulator and DebugLink support  - `./trezord-go -e 21324 -e 21325`.

Once the emulator is ready and the `device__connect` event is received `nemSignTransaction` method is [called]() via connect with the following payload

```javascript
{
    timeStamp: 1,
    fee: 2000000,
    type: 4100,
    deadline: 74735615,
    otherTrans: {
        timeStamp: 2,
        amount: 2000000,
        fee: 15000,
        recipient: 'TALICE2GMA34CXHD7XLJQ536NM5UNKQHTORNNT2J',
        type: 257,
        deadline: 67890,
        message: {
            payload: '746573745f6e656d5f7472616e73616374696f6e5f7472616e73666572',
            type: 1,
        },
        version: -1744830464,
        signer: 'c5f54ba980fcbb657dbaaa42700539b207873e134d2375efeab5f1ab52f87844',
    },
    version: -1744830464,
}
```

After last confirmation button is pressed emualtor returns 'Failure_Firmware'.
This is output from the emulator
```
Traceback (most recent call last):
 	 File "/trezor-core/src/trezor/wire/__init__.py", line 120, in session_handler
	 File "/trezor-core/src/trezor/wire/__init__.py", line 117, in session_handler
	 File "/trezor-core/src/trezor/wire/__init__.py", line 153, in protobuf_workflow
	 File "/trezor-core/src/trezor/wire/__init__.py", line 153, in protobuf_workflow
	 File "/trezor-core/src/trezor/wire/__init__.py", line 142, in protobuf_workflow
	 File "/trezor-core/src/apps/nem/signing.py", line 32, in sign_tx
	 File "/trezor-core/src/apps/nem/multisig/__init__.py", line 26, in aggregate_modification
```

Similar issues happens when calling `nemSignTransaction` with the following payload
```javascript
{
    timeStamp: 74649215,
    fee: 2000000,
    type: 16386,
    deadline: 74735615,
    message: {},
    mosaicId: {
        namespaceId: 'hellom',
        name: 'Hello mosaic',
    },
    supplyType: 1,
    delta: 1,
    version: -1744830464,
    creationFeeSink: 'TALICE2GMA34CXHD7XLJQ536NM5UNKQHTORNNT2J',
    creationFee: 1500,
}
```
Results in 
```
Traceback (most recent call last):
    File "/trezor-core/src/trezor/wire/__init__.py", line 120, in session_handler
    File "/trezor-core/src/trezor/wire/__init__.py", line 117, in session_handler
    File "/trezor-core/src/trezor/wire/__init__.py", line 153, in protobuf_workflow
    File "/trezor-core/src/trezor/wire/__init__.py", line 153, in protobuf_workflow
    File "/trezor-core/src/trezor/wire/__init__.py", line 142, in protobuf_workflow
    File "/trezor-core/src/apps/nem/signing.py", line 30, in sign_tx
    File "/trezor-core/src/apps/nem/mosaic/__init__.py", line 15, in supply_change
```

However it seems that this race condition doesn't happen when transport is started without DebugLink support - `./trezord-go -e 21325`

**Comment by matejcik** [comment]
I cannot currently reproduce this issue. It is quite old, so I'm going to go ahead and close it.

@mlejva if you can still reproduce the issue with current firmware, please leave a comment. Please also try if the issue persists in branch https://github.com/trezor/trezor-firmware/tree/matejcik/wip-debug-feedback
